[package]
name = "meteor"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.17.11"
polars = { version = "0.49.1", features = ["lazy", "json"] }
serde = "1.0.219"
serde-jsonlines = "0.7.0"

[dependencies.stem]
git = "https://github.com/minhnhdo/rust-stem"
